### ISSUE TITLE
Issue with connecting to MSSQL Pod from Mssql init Job

### ISSUE THREAD

**Issue by parthi007** [bplasmeijer/Sitecore-Symposium-2020-Containers-AKS#2]
While executing Init.ps1, the MSSQL Init Jobs fail. I Verified that the MSSQL Pod is created and running. 
Even I tried to redeploy both Mssql pod and rerun the jobs. 

Following are the logs from the Init Pods. Any help to troubleshoot this would be appreciated.
---------------------------------------------
Start publishing dacpacs
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Named Pipes Provider: Could not open a connection to SQL Server [53]. .
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if inst
ance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
sqlcmd exited with code 1
At C:\DeployDatabases.ps1:91 char:9
+         throw "sqlcmd exited with code $LASTEXITCODE"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (sqlcmd exited with code 1:Str 
   ing) [], RuntimeException
    + FullyQualifiedErrorId : sqlcmd exited with code 1

**Comment by VitaliZhur** [comment]
Hi @parthi007 how did you fix the issue?

**Comment by mjarosch** [comment]
I recently ran into this issue and believe it was caused by my corporate VPN. Once I disconnected from VPN, things started working again.
